version: 1
disable_existing_loggers: false
formatters:
  json:
    (): src.utils.logger.JsonFormatter
handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout
loggers:
  app:
    level: INFO
    handlers: [console]
    propagate: false
  httpx:
    level: WARNING
root:
  level: WARNING
  handlers: [console]
